[book]
authors = ["Paul Done"]
language = "en"
multilingual = false
src = "src"
title = "Practical MongoDB Aggregations Book"
description = "Learn about MongoDB Aggregations to develop effective and optimal data manipulation and analytics aggregation pipelines with this book, using the MongoDB Aggregation Framework (aggregate)"

[output.html]
cname = "www.practical-mongodb-aggregations.com"

